### ISSUE TITLE
Couldn't request network

### ISSUE THREAD

**Issue by wanyt** [kickstarter/android-oss#83]
When I run app success, I can not get data from network. and print log like this:

04-24 11:12:31.870 31832-31877/com.kickstarter.kickstarter.debug V/MixpanelAPI.DChecker: Cannot get https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=648a9a4c-4d30-474e-b242-dcfc79f2b868, file not found.
                                                                                         java.io.FileNotFoundException: https://decide.mixpanel.com/decide?version=1&lib=android&token=koala&distinct_id=648a9a4c-4d30-474e-b242-dcfc79f2b868
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:238)
                                                                                             at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                                             at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                                                                                             at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:91)
                                                                                             at com.mixpanel.android.mpmetrics.DecideChecker.getUrls(DecideChecker.java:290)
                                                                                             at com.mixpanel.android.mpmetrics.DecideChecker.getDecideResponseFromServer(DecideChecker.java:233)
                                                                                             at com.mixpanel.android.mpmetrics.DecideChecker.runDecideCheck(DecideChecker.java:88)
                                                                                             at com.mixpanel.android.mpmetrics.DecideChecker.runDecideChecks(DecideChecker.java:70)
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:269)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
04-24 11:12:31.942 31832-31877/com.kickstarter.kickstarter.debug V/MixpanelAPI.Messages: Cannot post message to http://dev/null. (Thread 4550)
                                                                                         java.net.ConnectException: failed to connect to dev/127.0.53.53 (port 80) after 2000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                                             at libcore.io.IoBridge.isConnected(IoBridge.java:234)
                                                                                             at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                                             at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                                             at java.net.Socket.connect(Socket.java:884)
                                                                                             at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
                                                                                             at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
                                                                                             at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67)
                                                                                             at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
                                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
                                                                                             at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:83)
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:423)
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:393)
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:268)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                          Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                                             at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                                             at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                                             at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                                             at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                                                             at java.net.Socket.connect(Socket.java:884) 
                                                                                             at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
                                                                                             at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
                                                                                             at com.android.okhttp.internal.http.SocketConnector.connectCleartext(SocketConnector.java:67) 
                                                                                             at com.android.okhttp.Connection.connect(Connection.java:152) 
                                                                                             at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
                                                                                             at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
                                                                                             at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
                                                                                             at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
                                                                                             at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433) 
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
                                                                                             at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245) 
                                                                                             at com.mixpanel.android.util.HttpService.performRequest(HttpService.java:83) 
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendData(AnalyticsMessages.java:423) 
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.sendAllData(AnalyticsMessages.java:393) 
                                                                                             at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:268) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:148) 

How should I solve this problem?

**Comment by LittleStupid** [comment]
I got the same problem.

**Comment by gpj008** [comment]
I got the sam problem on my phone also...

**Comment by gpj008** [comment]
I got the same problem on my phone also...

**Comment by rome753** [comment]
#21

**Comment by luoser** [comment]
yep, please refer to #21 and our readme: the oss repo is designed to build and run, but without production data (for now) from our server
